platform :ios, '9.0'

target 'ChatDemo-UI3.0' do
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage', '~> 3.7.3'
pod 'SDCycleScrollView', '~> 1.3'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'SVWebViewController', '~> 1.0'
pod 'Masonry'
end
